name: Documentation

on: push

jobs:
  readme:
    name: Update readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate and commit table of content
        uses: technote-space/toc-generator@v4.1.1
        with:
          TARGET_PATHS: README.md
          MAX_HEADER_LEVEL: 3
          COMMIT_MESSAGE: 'Docs: Update table of contents'
          PR_TITLE: Update table of contents (${PR_MERGE_REF})
      ##-- workflow-documentation-readme-steps --##
  ##-- workflow-documentation-jobs --##
